version: 2
jobs:
 build:
   machine:
     image: ubuntu-1604:202004-01
   steps:
     - checkout
     - run: |
         docker build -t trackit-api-tests .
         docker run -e TRACKIT_API_URL=$TRACKIT_API_URL -e TRACKIT_USERNAME=$TRACKIT_USERNAME -e TRACKIT_PASSWORD=$TRACKIT_PASSWORD -e TRACKIT_RT=10000 -e SLACK_CHANNEL=$SLACK_CHANNEL_TEST -e SLACK_TOKEN=$SLACK_TOKEN_TEST trackit-api-tests
workflows:
 version: 2
 commit:
   jobs:
    - build
 nightly:
   triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
   jobs:
     - build
